### ISSUE TITLE
issue: Header values must be RFC 7230 compatible strings

### ISSUE THREAD

**Issue by DominicGBauer** [osteel/openapi-httpfoundation-testing#1]
## Detailed description

I keep getting this error when trying to test my swagger docs using an endpoint 
`InvalidArgumentException: Header values must be RFC 7230 compatible strings.`

Here's the trace:

```
/var/www/vendor/nyholm/psr7/src/MessageTrait.php:201
/var/www/vendor/nyholm/psr7/src/MessageTrait.php:80
/var/www/vendor/symfony/psr-http-message-bridge/Factory/PsrHttpFactory.php:163
/var/www/vendor/osteel/openapi-httpfoundation-testing/src/HttpFoundation/HttpFoundationResponseAdapter.php:33
/var/www/vendor/osteel/openapi-httpfoundation-testing/src/ResponseValidator.php:57
/var/www/tests/Feature/SensorAPI/GatewayControllerTest.php:113
```

This is an example of the test I am trying to run: 
```
        $response = $this->get(
            'api/v1/sensor/gateways/gateway_name',
            [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
                'Authorization' => 'Bearer token'
            ]
        );

        $validator = ResponseValidatorBuilder::fromJson(storage_path('api-docs/api-docs.json'))->getValidator();

        $result = $validator->validate('/v1/sensor/gateways/gateway_name', 'get', $response->baseResponse);

        $this->assertTrue($result);
```

I'm not sure if it's a bug but all my other tests work when testing requests.

## Your environment

PHP 7.3.20
Laravel 8

**Comment by osteel** [comment]
Hi @DominicGBauer,

This error is not related to this package, but to [this one](https://github.com/Nyholm/psr7).

If I were you I would dump the headers passed on to [this function](https://github.com/Nyholm/psr7/blob/master/src/MessageTrait.php#L178) to try and spot the faulty one.

Closing this now, but let me know if I can be of further assistance.

**Comment by DominicGBauer** [comment]
@osteel thanks so much for the prompt response.

I've made an issue in the relevant package [here ](https://github.com/Nyholm/psr7/issues/167).

Thanks again!
