### ISSUE TITLE
laravel 6

### ISSUE THREAD

**Issue by Barmunksu** [osteel/openapi-httpfoundation-testing#10]
Hello, this pkg not working with laravel 6?

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Root composer.json requires osteel/openapi-httpfoundation-testing ^0.6.0 -> satisfiable by osteel/openapi-httpfoundation-testing[v0.6].
>     - osteel/openapi-httpfoundation-testing v0.6 requires symfony/http-foundation ^5.3 -> found symfony/http-foundation[v5.3.0-BETA1, ..., 5.4.x-dev] but the package is fixed to v4.4.23 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by osteel** [comment]
Hi, it seems that you need to update `symfony/http-foundation` first

**Comment by Barmunksu** [comment]
@osteel 

https://packagist.org/packages/laravel/framework#v6.20.32
- symfony/http-foundation: ^4.3.4

**Comment by osteel** [comment]
@Barmunksu I see, thanks. It would probably make sense to make this package compatible with both HttpFoundation 4+ and 5+ indeed. Will have a look when I get the chance

**Comment by osteel** [comment]
@Barmunksu let me know if v6.0.1 fixed it
