### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by jokaorgua** [osteel/openapi-httpfoundation-testing#13]
Would be nice to have Symfony 6 support. AS for me it should be enough to change supported versions in composer

**Comment by osteel** [comment]
Hi, thanks for the issue. Yeah I need to go through this package's dependencies and broaden support overall. Will try and give it a shot over the weekend – bear with!

**Comment by osteel** [comment]
Should be fixed with [v0.7](https://github.com/osteel/openapi-httpfoundation-testing/releases/tag/v0.7) – let me know if any issues
