### ISSUE TITLE
Testing against OpenAPI Specification doesnt seem to work as intended.

### ISSUE THREAD

**Issue by K2ouMais** [osteel/openapi-httpfoundation-testing#17]
Hi there,

first of all this is not an issue.

This is a package that I alway wanted to have to validate my API endpoints against the OpenAPI documentation.

It seems that I am missing something and would love to get some help to get this to work.

I am using Laravel with Docker (Laravel Sail) and I use Stoplight Studio to get some help and to write my OpenAPI definition.

I used exactly the same Example I saw on twitter, but it seems I am getting some problems getting it to work the way I want it to have.

For a better example I recorded a video that shows where my problem is.

https://youtu.be/Gzadpf3MyCI

Thank you in advance.

PS: If you have some questions let me know.

**Comment by osteel** [comment]
Hi João,

Have you tried adding `additionalProperties: false` as suggested on Twitter?

Like this:

```json
"availability": {
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "gleif-api": {
      ...
    }
  }
}
```

**Comment by K2ouMais** [comment]
Will try that and let you know 👍🏻

**Comment by K2ouMais** [comment]
OK, this seems to work, but how do I test if the API is outputing a new property, that isnt described in the OpenAPI docs?

I just have inserted a new property in my Resource and the test is still passing. 

If I rename a property, the test fails and that is good.

The thing is, that I cant forget to put "additionalProperties" every time I change the docs. 

Stoplight Studio seems to override this every time with every change. 😢 

Thanks in advance.

**Comment by osteel** [comment]
> but how do I test if the API is outputing a new property, that isnt described in the OpenAPI docs?

By using `"additionalProperties": false` 😉 

I don't personally use Stoplight Studio – maybe get in touch with them, as it may be an issue with there software?

> It seems that when I have a field as with type string or null, that it throws an Exception that the field cant be null

I would need to see your OpenAPI schema

**Comment by philsturgeon** [comment]
If you need help from the Stoplight crew you'll find loads of them on the discord. https://discord.com/invite/stoplight

**Comment by osteel** [comment]
I suggest you get in touch with Stoplight @K2ouMais, maybe through their Discord as suggested by @philsturgeon. Closing this for now because I don't think your issue is related to this package. Feel free to reach out if there's anything else though!
