### ISSUE TITLE
more debug information

### ISSUE THREAD

**Issue by jamesRUS52** [osteel/openapi-httpfoundation-testing#20]
Hello

How can I find out what field of response is incorrect ?

Osteel\OpenApi\Testing\Exceptions\ValidationException : Body does not match schema for content-type "application/json" for Response [get /entities/{id} 200]: Value '2022-07-31T21:00:00.000000Z' does not match format date of type string

**Comment by osteel** [comment]
Hi James,

Yeah the underlying errors aren't always 100% specific. As you can see [here](https://github.com/osteel/openapi-httpfoundation-testing/blob/main/src/Exceptions/ValidationException.php#L23) I'm already concatenating the error messages from the chain of exceptions coming from [this package](https://github.com/thephpleague/openapi-psr7-validator), to give as much info as possible to the end user.

This is the package responsible for the actual validation, and if you go check its issues you'll see that some other people have similar questions (see [here](https://github.com/thephpleague/openapi-psr7-validator/issues/153) for instance).

That being said I just noticed [this specific comment](https://github.com/thephpleague/openapi-psr7-validator/issues/153#issuecomment-1035059721) that might help

**Comment by jamesRUS52** [comment]
Thanks

**Comment by osteel** [comment]
Hey @jamesRUS52 – had a closer look and I think I managed to [improve](https://github.com/osteel/openapi-httpfoundation-testing/pull/21) the error message. Would you mind installing [v0.7.2](https://github.com/osteel/openapi-httpfoundation-testing/releases/tag/v0.7.2) and let me know if that helps?

**Comment by jamesRUS52** [comment]
Yes, it amazing

Property [created] does not match the expected value.
Failed asserting that two strings are identical.
Expected :'Fri Jul 01 2022 19:25:55 GMT+0300'
Actual   :'2022-07-01T16:25:55.000000Z'

Thanks a lot
