### ISSUE TITLE
Is there any way to validate response objects recursively?

### ISSUE THREAD

**Issue by VAZaitesev** [osteel/openapi-httpfoundation-testing#24]
It looks like the validator fails to check objects inside a request

## Detailed description

I've modified responce in example project so it looks like this:

```
Route::post('/test', function (Request $request) {
    return response()->json([
        'status' => 200,
        'success' => true,
        'data' => [
            'here' => 'here',
        ],
    ]);
});
```

Also I've modified openapi defenition:

```
  /test:
    post:
      tags:
        - "Authorization"
      summary: "login into user account"
      description: "Stores new access tokens in DB. returns stored access tokens and user data"
      requestBody:
        $ref: '#/components/requestBodies/LoginRequest'
      responses:
        "200":
          $ref: "#/components/responses/LoginResponse"

  responses:
    LoginResponse:
      description: "successful operation"
      content:
        application/json:
          schema:
            type: object
            required:
              - status
              - success
              - data
            properties:
              status:
                type: integer
                example: 200
              success:
                type: boolean
                example: true
              data:
                type: object
                properties:
                  accessToken:
                    type: integer
                  refreshToken:
                    type: integer

  requestBodies:
    LoginRequest:
      content:
        application/json:
          schema:
            type: object
            properties:
              email:
                type: string
                example: "mail@mail.mail"
              password:
                description: "min 6 symbols"
                type: string
                example: "password123"
            required:
              - email
              - password
```
as you can see actual response and openapi response body object doesn't match. a real one returns only 'here' => 'here' in data while open api expects 'refreshToken' => 'string' and 'accessToken' => 'string'

But tests are passing anyway which was not expected in this case

## Context

I was expecting it is possible to validate response body entirely

## Possible implementation

Unfortunately I'm not experienced enough to offer any concrete solutions

## Your environment

openapi-httpfoundation-testing example laravel project launched via sail

php8.1, Ubuntu 22.04

**Comment by osteel** [comment]
Hey,

That's actually a fairly common "mistake". In your example, the request payload you're submitting is actually valid, since the only attribute that is required as per your OpenAPI definition is `data`, and your request has it.

In this section:

```yaml
data:
  type: object
  properties:
    accessToken:
      type: integer
    refreshToken:
      type: integer
```

All you're saying is "_if_ `accessToken` is present, then it has to be an integer". Same with `refreshToken`. But you're not saying that either of those are required, nor that other attributes are forbidden.

If you want these attributes to be required and other attributes to be forbidden, you should update the above section this way:

```yaml
data:
  type: object
  additionalProperties: false
  required:
    - accessToken
    - refreshToken
  properties:
    accessToken:
      type: integer
    refreshToken:
      type: integer
```

Hope this helps

**Comment by VAZaitesev** [comment]
yep, looks like it helps. Thank you very much.  But is it possible to test request bodies in the same way as we are doing is with response bodies?

**Comment by osteel** [comment]
I meant "response" in my answer, rather than "request" – sorry. But yes, you can also validate request objects, using the same methods as response objects (there's a mention of that in the [documentation](https://github.com/osteel/openapi-httpfoundation-testing#usage))

**Comment by VAZaitesev** [comment]
Oh I've missed this sorry. Is there any simple way for laravel to retrieve this request right in test?

**Comment by VAZaitesev** [comment]
I've found a solution for laravel
you can do it as folows

```
$validator = ValidatorBuilder::fromYamFile(...);
$request = app()->make(ReqeustName::clas);
$validator->post($request, ....);
```
