### ISSUE TITLE
inverse valiation as a possiblity.

### ISSUE THREAD

**Issue by borisson** [osteel/openapi-httpfoundation-testing#41]
## Detailed description

This package works great to validate that all properties that are in the schema are also in the response, but I would like to also validate that every single property on my response is part of the schema.

## Context

We're using https://orval.dev/ to generate typescript types based on the schema and sometimes our frontend people yell at me to add typing/schema, I would like our pipelines to yell at me instead.

How can it benefit other users?

^ See above.

Not obligatory, but suggest an idea for implementing addition or change.

I think it should be probably an optional setting, because I'm not sure everyone will want to be this strict about their responses matching schemas.

**Comment by osteel** [comment]
Heya

After a quick read of your issue it sounds like adding `additionalProperties: false` to your schema might do the trick. See [this issue](https://github.com/osteel/openapi-httpfoundation-testing/issues/17)

Let me know if that helps!

**Comment by borisson** [comment]
That helps, thank you so much for the help!
